version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - back-postgres

  back:
    depends_on:
      - postgres
    build: ${NAME_BACK}
    ports:
      - "4000:4000"
    environment:
      TZ: Europe/Paris
    restart: always
    networks:
      - back-postgres
      - front-back
    volumes:
      - front-files:/front/

  front:
    depends_on:
      - back
    build: ${NAME_FRONT}
    ports:
      - "80:3000"
    environment:
      TZ: Europe/Paris
    restart: always
    networks:
      - front-back
    volumes:
      - front-files:/front/

networks:
  back-postgres:
    driver: bridge
  front-back:
    driver: bridge

volumes:
  db-data:
  front-files: 